/**
 * PRIMARY NAVIGATION: the single source of truth for header (and, later,
 * footer) navigation, per docs/08 section 3's extensibility note: "Columns
 * are data-driven from the navigation config, so IA changes propagate to
 * header and footer together."
 *
 * Five items plus the "Become a Member" action (docs/05 section 3.1). A
 * sixth top-level item is a signal that something belongs one level down,
 * do not add one without revisiting that document.
 *
 * REGIONS IS DELIBERATELY A SIMPLE LINK, NOT A PANEL, FOR NOW.
 *
 * docs/05 section 3.1 specifies a mega-panel for About, Programmes AND
 * Regions. About's and Programmes' children are all real, buildable routes
 * (registered in src/lib/page-meta.ts's pageMeta, so linking to them before
 * their pages exist only warns in scripts/check-seo.mjs rather than failing
 * the build). The six individual region routes (/regions/ankole/ etc.) are
 * NOT in that registry: they are collection-driven pages generated by
 * WUFPA-041, which has not run yet. Linking to them now would fail the
 * build's internal-link check, and a panel that shows six names with no
 * working destination is the same "dead link" failure mode this whole
 * component exists to avoid (docs/08 section 2, on the prototype's dead
 * "Donate" anchor).
 *
 * Once WUFPA-041 lands, add a `children` array here to upgrade Regions to a
 * panel: a config change, not a component change (docs/08 section 3).
 *
 * Source: docs/05 section 2 (sitemap), section 3.1 (primary navigation) ·
 * docs/08 section 3 (PrimaryNav) · WUFPA-018
 */
import type { NavItem, FooterColumn } from './types';

export const primaryNav: NavItem[] = [
  {
    label: 'About',
    href: '/about/',
    children: [
      { label: 'About WUFPA', href: '/about/' },
      { label: 'Our story', href: '/about/history/' },
      { label: 'Governance', href: '/about/governance/' },
      { label: 'Legal status', href: '/about/legal/' },
      { label: 'Leadership', href: '/leadership/' },
    ],
  },
  {
    label: 'Programmes',
    href: '/programmes/',
    children: [
      { label: 'All programmes', href: '/programmes/' },
      { label: 'Training & capacity building', href: '/programmes/training/' },
      { label: 'Advocacy, rights & anti-piracy', href: '/programmes/advocacy/' },
      { label: 'The WUFPA Kibanda Initiative', href: '/programmes/kibanda/' },
      { label: 'Distribution & market access', href: '/programmes/distribution/' },
      { label: 'Film competitions & awards', href: '/programmes/competitions/' },
      { label: 'International exposure', href: '/programmes/international/' },
    ],
  },
  {
    label: 'Regions',
    href: '/regions/',
    children: [
      { label: 'All six sub-regions', href: '/regions/' },
      { label: 'Ankole (Rwizi)', href: '/regions/ankole/' },
      { label: 'Kigezi', href: '/regions/kigezi/' },
      { label: 'Rwenzori', href: '/regions/rwenzori/' },
      { label: 'Tooro', href: '/regions/tooro/' },
      { label: 'Bunyoro', href: '/regions/bunyoro/' },
      { label: 'Greater Bushenyi', href: '/regions/greater-bushenyi/' },
    ],
  },
  { label: 'Membership', href: '/membership/' },
  { label: 'News', href: '/news/' },
];

export const becomeAMember: NavItem = { label: 'Become a Member', href: '/membership/join/' };

/**
 * FOOTER COLUMNS: docs/05 section 3.4. Every link here resolves to a route
 * registered in src/lib/page-meta.ts's pageMeta, so linking to it before the
 * page exists only warns in scripts/check-seo.mjs rather than failing the
 * build: the same rule that shaped Regions above.
 *
 * "Partners" (column 1, viewing WUFPA's existing partners) and "Partner with
 * us" (column 3, becoming one) point at the same /partners/ page under
 * different anchor text: docs/05 lists them as two distinct entries in two
 * different columns, and there is no second URL for the second framing.
 *
 * Column 4 (Contact) omits an association email and telephone number
 * entirely: `⟦Q3⟧` is unanswered (src/lib/site-config.ts: `email` and
 * `telephone` are both `null`), and the working rule throughout this
 * codebase is that an unresolved fact is omitted, never guessed at.
 */
export const footerColumns: FooterColumn[] = [
  {
    heading: 'WUFPA',
    links: [
      { label: 'About', href: '/about/' },
      { label: 'Our story', href: '/about/history/' },
      { label: 'Leadership', href: '/leadership/' },
      { label: 'Governance', href: '/about/governance/' },
      { label: 'Legal status', href: '/about/legal/' },
      { label: 'Partners', href: '/partners/' },
    ],
  },
  {
    heading: 'What we do',
    links: [
      { label: 'Programmes', href: '/programmes/' },
      { label: 'Training & capacity building', href: '/programmes/training/' },
      { label: 'Advocacy, rights & anti-piracy', href: '/programmes/advocacy/' },
      { label: 'The WUFPA Kibanda Initiative', href: '/programmes/kibanda/' },
      { label: 'Distribution & market access', href: '/programmes/distribution/' },
      { label: 'Film competitions & awards', href: '/programmes/competitions/' },
      { label: 'International exposure', href: '/programmes/international/' },
    ],
  },
  {
    heading: 'Get involved',
    links: [
      { label: 'Become a member', href: '/membership/join/' },
      { label: 'Membership', href: '/membership/' },
      { label: 'WUFM SACCO', href: '/sacco/' },
      { label: 'Partner with us', href: '/partners/' },
      { label: 'Support WUFPA', href: '/support/' },
      { label: 'Guilds', href: '/guilds/' },
      { label: 'Regions', href: '/regions/' },
    ],
  },
];

/** Legal footer links, base row. */
export const legalLinks: { label: string; href: string }[] = [
  { label: 'Privacy', href: '/legal/privacy/' },
  { label: 'Terms', href: '/legal/terms/' },
  { label: 'Accessibility', href: '/legal/accessibility/' },
];
